import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import FAQ from './sections/FAQ/FAQ'
import Home from './sections/Home/Home'
import Footer from './components/Footer/Footer'
import NavBar from './components/NavBar/NavBar'
import About from './sections/About/About'
import Menu from './sections/Menu/Menu'
import FindUs from './sections/FindUs/FindUs'
import Scroller from './components/Scroller/Scroller'
import { useState } from 'react'
import Announce from './components/Modal/Announce'
import Modal from './components/Modal/Modal'
import { openAnn } from '@/materials/strings/Announcement'

const inter = Inter({ subsets: ['latin'] })

export default function App() {
  const [announce, isAnnounce] = useState(openAnn)

  const closeModal = () => {
    isAnnounce(false)
  }

  return (
    <>
      <Head>
        <title>Indo Restaurant at Toa Payoh, Singapore | Three by Garamika</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>
        <Home />
        <About />
        <Menu />
        <FindUs />
        <FAQ />
      </main>
      <Scroller />
      <Footer />
      {announce && <Modal component={<Announce close={closeModal} />} />}
    </>
  )
}
